<?php

return [
    'paginate' => 6,
    'zero' => 0,
    'min' => 1,
    'two' => 2,
    'three' => 3,
    'rows' => 4,
    'four' => 4,
    'five' => 5,
    'six' => 6,
    'seven' => 7,
    'eight' => 8,
    'nine' => 9,
    'ten' => 10,
    'eleven' => 11,
    'timeout_cookie' => 86000,
    'unset_cookie' => -86000,
    'vnd' => 'VND',
    'cols' => 54,
    'hundred' => 100,
    'million' => 1000000,
    'type_first' => 1,
    'type_second' => 2,
    'customer' => 'customer',
    'admin' => 'admin',
    'mail_admin' => 'admin@gmail.com',
    'thousand' => 1000,
    'five_hundred' => 500,
    'mail_admin_receive' => 'nguyenngon95@gmail.com',

];
